id = "common-lisp"
name = "Common Lisp"
version = "1.1.0"
schema_version = 1
authors = ["Evgeniy Tyurkin <etyurkin@kwarks.org>"]
description = "Common Lisp support for Zed"
repository = "https://github.com/etyurkin/zed-cl"

[grammars.commonlisp]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-commonlisp"
rev = "4d2a2247bb0ec117193ef33e3ce546a6781c5bf5"

[language_servers.common-lisp]
name = "zed-cl"
language = "Common Lisp"
